// Generated by scripts/generate-splash.mts. Do not edit by hand.
// Re-run `pnpm gen:splash` after icon or palette changes.

export const APPLE_SPLASH_STARTUP_IMAGES: Array<{
  url: string;
  media?: string;
}> = [
  {
    "url": "/splash/apple-splash.png"
  },
  {
    "url": "/splash/apple-splash-dark.png",
    "media": "(prefers-color-scheme: dark)"
  }
];
