import type { Metadata, Viewport } from "next";
import { Geist, IBM_Plex_Mono, Newsreader } from "next/font/google";
import "./globals.css";
import { ServiceWorkerRegistrar } from "./_components/service-worker-registrar";
import { APPLE_SPLASH_STARTUP_IMAGES } from "@/lib/pwa/splash-startup-images";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  style: ["normal", "italic"],
  display: "swap",
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Coach Casey: a reflective partner for marathoners",
  description:
    "Most running apps tell you what to do. Coach Casey doesn't. It sits alongside your existing plan and makes sense of what just happened, every run, every week.",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Coach Casey",
    // Universal apple-touch-startup-image: one image scaled by iOS to
    // fit any device, plus a dark variant gated on prefers-color-scheme.
    // The previous per-device matrix needed updating every time Apple
    // shipped a new iPhone; this approach is future-proof and trims
    // public/splash from 30 PNGs / 928 KB to 2 PNGs / 64 KB.
    // Generated by scripts/generate-splash.mts.
    startupImage: APPLE_SPLASH_STARTUP_IMAGES,
  },
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#faf8f5" },
    { media: "(prefers-color-scheme: dark)", color: "#131217" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${newsreader.variable} ${plexMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-paper text-ink font-sans overflow-x-hidden">
        <ServiceWorkerRegistrar />
        {children}
      </body>
    </html>
  );
}
