/**
 * Generate iOS PWA splash screens from the existing 512x512 icon.
 *
 * iOS without apple-touch-startup-image falls back to the manifest's
 * background_color + the largest icon scaled up: readable but generic.
 * We render a high-resolution splash with the brand "C" mark centred
 * on a paper background and let iOS scale it to fit whatever device the
 * user is on. The app is light-only, so there is a single light splash.
 *
 * Why one universal image instead of a per-device matrix: Apple ships
 * a new iPhone every September, and `apple-touch-startup-image` only
 * matched on exact device-width / device-height / pixel-ratio in older
 * iOS. The previous version generated 30 PNGs to cover known devices
 * but iPhone 17 Pro and any future model fell back to iOS's default.
 * iOS 13+ honours an apple-touch-startup-image without a media query
 * as a generic fallback, so a single high-res image scaled by the OS
 * works for any device, present and future, with zero maintenance.
 *
 * Run via: `pnpm gen:splash`
 *
 * Outputs to public/splash/. Re-run only when the icon or palette
 * changes; the generated files are committed.
 */

import sharp from "sharp";
import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(fileURLToPath(import.meta.url), "..", "..");
const ICON_PATH = join(ROOT, "public", "icon-512.png");
const OUT_DIR = join(ROOT, "public", "splash");

// 9:19.5 portrait aspect at iPhone 16/17 Pro Max resolution. Tall enough
// that any iPhone scales down cleanly; iPad sees a taller-than-screen
// image scaled to fit width, with the matching background colour filling
// the top and bottom bars. Either way the centred icon stays centred.
const SPLASH_WIDTH = 1320;
const SPLASH_HEIGHT = 2868;

// Brand palette mirrored from app/globals.css.
const PAPER_LIGHT = { r: 0xfa, g: 0xf8, b: 0xf5 };

type SplashEntry = {
  url: string;
  media?: string;
};

async function clearOldSplashes() {
  await mkdir(OUT_DIR, { recursive: true });
  const existing = await readdir(OUT_DIR);
  for (const name of existing) {
    if (name.startsWith("apple-splash-") && name.endsWith(".png")) {
      await unlink(join(OUT_DIR, name));
    }
  }
}

async function generate() {
  await clearOldSplashes();
  const iconBuf = await readFile(ICON_PATH);

  // Icon takes ~22% of the shorter dimension so it lands at a comfortable
  // size on every screen, neither cramped on small phones nor lost on iPad.
  const iconSize = Math.round(Math.min(SPLASH_WIDTH, SPLASH_HEIGHT) * 0.22);
  const resizedIcon = await sharp(iconBuf)
    .resize(iconSize, iconSize, { fit: "contain" })
    .png()
    .toBuffer();

  await sharp({
    create: {
      width: SPLASH_WIDTH,
      height: SPLASH_HEIGHT,
      channels: 3,
      background: PAPER_LIGHT,
    },
  })
    .composite([{ input: resizedIcon, gravity: "center" }])
    .png({ compressionLevel: 9 })
    .toFile(join(OUT_DIR, "apple-splash.png"));

  // Single light splash; no prefers-color-scheme media query.
  const entries: SplashEntry[] = [{ url: "/splash/apple-splash.png" }];

  // Emit the metadata array as a TS module the layout can import. Keeping
  // it as data (not embedded in layout.tsx) means future tweaks to the
  // image set don't churn the layout file.
  const tsPath = join(ROOT, "lib", "pwa", "splash-startup-images.ts");
  await mkdir(join(ROOT, "lib", "pwa"), { recursive: true });
  const ts = `// Generated by scripts/generate-splash.mts. Do not edit by hand.
// Re-run \`pnpm gen:splash\` after icon or palette changes.

export const APPLE_SPLASH_STARTUP_IMAGES: Array<{
  url: string;
  media?: string;
}> = ${JSON.stringify(entries, null, 2)};
`;
  await writeFile(tsPath, ts, "utf8");

  console.log(
    `[splash] generated ${entries.length} universal images (${SPLASH_WIDTH}×${SPLASH_HEIGHT})`,
  );
}

generate().catch((err) => {
  console.error(err);
  process.exit(1);
});
